services:
  backend:
    build:
      context: ./backend
    container_name: hotel-backend
    ports:
      - "3340:3340"
    volumes:
      - ./backend/data:/app/data
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: hotel-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped